### ISSUE TITLE
Get a security review

### ISSUE THREAD

**Issue by wresuolc** [bwinton/SnoozeTabs#121]
I need a close-to-done .xpi to send to the security team for a review.  It doesn't need to have final touches, but the basic structure should be there.  Probably after metrics lands?

**Comment by lmorchard** [comment]
Metrics has landed, but still need to switch over to the new broker library (#122) - thinking that's the only blocker left for this?

**Comment by lmorchard** [comment]
#136 is the PR for moving to the new broker library. Still needs merging, but I'm not expecting it to have to change too significantly in terms of what gets submitted & when.

There's a build of this PR here on CircleCI: https://55-74497025-gh.circle-artifacts.com/0/tmp/circle-artifacts.unkLINQ/snoozetabs-1.0.9.zip

It's an unsigned .zip rather than a signed .xpi - if it helps things get going sooner, we could use that build. Or, we can wait until the PR is merged and I can to a production branch push

**Comment by bwinton** [comment]
@clouserw: We've done this, so can close this bug, right?

**Comment by lmorchard** [comment]
Yup, sounds like we did!
