### ISSUE TITLE
did we want to use backticks?

### ISSUE THREAD

**Issue by wresuolc** [bwinton/SnoozeTabs#174]
Code review from AMO only turned up a single nit:  They thought we wanted to use backticks at https://github.com/bwinton/SnoozeTabs/blob/3595938eb5b3bab3b7af89a03d767dcb8551716c/src/background.js#L265

**Comment by bwinton** [comment]
We _love_ [using backticks](https://weblog.latte.ca/blake/tech/firefox/templates.html)!  But in that case, it's already in [a set of backticks](https://github.com/bwinton/SnoozeTabs/blob/3595938eb5b3bab3b7af89a03d767dcb8551716c/src/background.js#L242), so we probably shouldn't change that.  🙂

**Comment by wagnerand** [comment]
Good call. But are you sure this works as intended?

**Comment by lmorchard** [comment]
Yeah, this works as intended. The favicon flips between the site's original one and our icon data URL. The `'${iconData}'` part gets filled in with that data URL because [the whole block of HTML is a backtick template starting from line 242](https://github.com/bwinton/SnoozeTabs/blob/3595938eb5b3bab3b7af89a03d767dcb8551716c/src/background.js#L242)

**Comment by wagnerand** [comment]
Yeah I realized after @bwinton's comment. I just wasn't sure this actually works.

**Comment by bwinton** [comment]
I mean, to be fair, I wasn't sure it would work as I was writing it, either, but it seems to…  😉
