### ISSUE TITLE
Days and Months names

### ISSUE THREAD

**Issue by belkacem77** [bwinton/SnoozeTabs#185]
SnoozeTabs picks  days and months names of the system locale not the browser locale.

**Comment by bwinton** [comment]
It picks the day and month names from [the accept-languages](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n/getAcceptLanguages).  I suppose, since this is part of the browser's UI, we should probably switch it to use the [UI language](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n/getUILanguage) instead…
