### ISSUE TITLE
Restore problem

### ISSUE THREAD

**Issue by stefan-ioan-2017** [bwinton/SnoozeTabs#230]
When you have multiple tabs open and restore one of Manage Snoozed Tabs he did not return to original position, which was moved Snoozed ... For example, if when I moved was the 3rd tab, on restoration is placed last.

**Comment by SoftVision-PaulOiegas** [comment]
Currently, Snooze Tabs does not focuses the restored tab and I don't think it will. Also, Firefox focuses any new tab opened. So think at the next scenario. 
You have lots of opened tabs, one of the old snoozed tabs is restored on its original position, but since you have snoozed it, you opened like 20 new more tabs. 
In this case the restored tab will probably go unnoticed unless you go trough entire list and look for a distinctive notification generated from Snoozed Tabs. 

Restoring a snoozed tab on the last (newest) position, lowers the chance of going unnoticed. At least this is my opinion on this matter.

**Comment by bwinton** [comment]
Yeah, what Paul said.  Also, it's unclear where we should open a restored tab.  Always at the position it was?  (What if there aren't that many tabs anymore?)  Beside the tab it was previously beside?  (What if that tab was closed?  Or moved to a different window?)  There are a lot of complications here, and I'm not convinced any of the other options are significantly better than what we currently do.

**Comment by stefan-ioan-2017** [comment]
Paul, thanks for the reply. You're right ... It's good ... What I wanted so can not ... Thanks again for your answer.
