### ISSUE TITLE
The "REAL SOON NOW!" icon has a small delay when accesing the SnoozedTabs Panel

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#246]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.15 (built on 07/03/2017)

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 07/03/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website (e.g. www.wikipedia.org).
2. Click on the SnoozedTabs button.
3. Repeat Step 2 few times and observe the "REAL SOON NOW!" icon behaviour.

[Expected result]:
- "REAL SOON NOW!" icon is displayed instantly.

[Actual result]:
- "REAL SOON NOW!" icon has a slight delay.

[Notes]:
- This is also reproducible when clicking the SnoozedTabs button from the Burger Menu.
- Please see the Screen Cast attached:
![delay icon](https://cloud.githubusercontent.com/assets/26000308/23662692/0e2ffcb2-0359-11e7-9694-ec653d29936e.gif)

**Comment by lmorchard** [comment]
This is basically the same delay as from #79, just deferred down into panel rendering. The pre-rendered HTML we just added is missing the "Real Soon Now" item, because the production build does not include it. Adding the "Real Soon Now" item is delayed by the same factors that delayed the whole panel being displayed before the changes in 02ef075900dc07b51a1fcd8b0a37bac452a8f750
