### ISSUE TITLE
Snooze Tabs isn't compatible on firefox 52.0.2.6291 x86

### ISSUE THREAD

**Issue by walthinking** [bwinton/SnoozeTabs#312]
The opened JavaScript window has been closed before I clicked the window or it's buttons.

**Comment by SoftVision-EmilPasca** [comment]
@walthinking Thank you for reporting this issue!
I haven't managed to test this on the specified Firefox version(52.0.2.6291 x86) you are using since I wasn't able to find it and download it.
Could you download the latest Firefox Release from [here ](https://www.mozilla.org/en-US/firefox/new/) and check if the issue is still reproducible?

**Comment by walthinking** [comment]
Nice! It runs normally on Firefox version(53.0 x86).
