### ISSUE TITLE
Blank ETA and unpressable buttons

### ISSUE THREAD

**Issue by yuvallanger** [bwinton/SnoozeTabs#328]
I try pressing the different options and nothing happens, including when pressing `Manage Snoozed Tabs`.

![2017scrot](https://cloud.githubusercontent.com/assets/536362/26507364/b8a46424-4258-11e7-8c41-6631e72e1f80.png)

**Comment by SoftVision-CarmenFat** [comment]
Hi @yuvallanger and thank you for submitting this issue.

Can you please give us more details about your system, such as what Firefox version you have installed, operating system and other add-ons you may have installed?

**Comment by yuvallanger** [comment]
Ubuntu 16.10

Firefox 53.0.3 (64-bit)

`apt show firefox` says `53.0.3+build1-0ubuntu0.17.04.2`

Addon list from about:debugging#addons:

Canadian English Dictionary
Containers Experiment
English (GB) Language Pack
English (South Africa) Language Pack
Hebrew spell-checking dictionary (from HSpell)
Multi-process staged rollout
Pocket
Privacy Badger
Pulse
Self-Destructing Cookies
Shield Recipe Client
snoozetabs
Tab Center
Test Pilot
uBlock Origin
Web Compat

**Comment by sharonbautista** [comment]
This issue was also reported yesterday by a participant in the Test Pilot diary study I'm currently running: 

> The SNOOZED TABS feature is not working for me at all on any website that I am visiting today. 

The feature icon shows in the upper right hand of my Firefox browser. Yes, I am able to click on it. However, after clicking on it I cannot select any of the choices from the drop-down menu of the listed Snooze Times.

In addition, I clicked repeatedly on the times in the drop down menu to see if they would be saved and show up within the Upcoming Snooze Times window and none of them did. 

Attached to this e-mail are (2) Screen Shots from different websites (Walmart.com and RestorationHardware.com) showing this. 

![snoozed tabs restoration hardware com unable to select any snooze times from drop down menu](https://cloud.githubusercontent.com/assets/17853015/26588110/f15c9e26-4519-11e7-8ae6-477aa4d73061.jpg)
![snoozed tabs walmart com no upcoming snoozes screen shot](https://cloud.githubusercontent.com/assets/17853015/26588111/f1ec1ab0-4519-11e7-8a73-20e0e3e4b1cd.jpg)

**Comment by lmorchard** [comment]
This state indicates that something went wrong during the startup of the Snooze Tabs panel. Do you happen to have any errors that come up under the Browser Console? (Tools Menu > Web Developer > Browser Console)

**Comment by yuvallanger** [comment]
I have checked the Browser Console and spotted this:

```
RangeError: invalid language tag: en-US.UTF_8  background.js:2:25321
    CanonicalizeLocaleList self-hosted:1535:17
    InitializeDateTimeFormat self-hosted:2210:28
    <anonymous>
moz-extension://f47dfbde-8181-49e9-a28c-8c3ff0b0dbc6/background.js:2:25321
    <anonymous>
moz-extension://f47dfbde-8181-49e9-a28c-8c3ff0b0dbc6/background.js:1:2
```

Running Firefox with `env LC_ALL=C firefox` makes the problem
disappear.

I might have misconfigured the locale environment variables.

```
$ locale
LANG=en_IL.UTF-8
LANGUAGE=en_IL.UTF-8:en
LC_CTYPE="en_IL.UTF-8"
LC_NUMERIC="en_IL.UTF-8"
LC_TIME="en_IL.UTF-8"
LC_COLLATE="en_IL.UTF-8"
LC_MONETARY="en_IL.UTF-8"
LC_MESSAGES="en_IL.UTF-8"
LC_PAPER="en_IL.UTF-8"
LC_NAME="en_IL.UTF-8"
LC_ADDRESS="en_IL.UTF-8"
LC_TELEPHONE="en_IL.UTF-8"
LC_MEASUREMENT="en_IL.UTF-8"
LC_IDENTIFICATION="en_IL.UTF-8"
LC_ALL=
```

**Comment by lmorchard** [comment]
Cannot reproduce, going to close for now.
