### ISSUE TITLE
Picking a time doesn't work properly with privacy.resistFingerprinting = true

### ISSUE THREAD

**Issue by nkestrel** [bwinton/SnoozeTabs#334]
STR:
1. `privacy.resistFingerprinting = true` (FF55+)
2. `Snooze tab until...` -> `Pick a Date/Time`
3. Current time incorrectly using UTC.
4. Specify time a few minutes after current local time.
5. Confirmation appears indicating UTC time the tab will be restored.
6. Tab is not restored at expected local time.

**Comment by SoftVision-EmilPasca** [comment]
I can confirm that the issue is reproducible on Windows 10 and Mac OS with Firefox Beta (55.0b7-20170706085221) and Nightly (56.0a1-20170710030203) with the pref "privacy.resistFingerprinting" set to "true".

According to bug [1308340](https://bugzilla.mozilla.org/show_bug.cgi?id=1308340), when this pref is enabled, it causes a number of system properties to be hidden including the system time zone. Considering this I assume that this is the intended behavior.

However, I will leave this open to see an opinion from the developer team. Maybe we can notify the user in some way when this pref is set.

@lmorchard Can you please have a look at this?

**Comment by lmorchard** [comment]
We definitely have no access to Firefox preferences from the WebExtension APIs. So, our hands seem tied on this. We're using the [built-in i18n APIs for date & time](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat), so this might be an upstream issue
