### ISSUE TITLE
Investigate switching to Redux.

### ISSUE THREAD

**Issue by bwinton** [bwinton/SnoozeTabs#34]
I think the message passing would integrate nicely with our background script, and it has made other codebases I've worked on simpler in the past.

**Comment by lmorchard** [comment]
I'd started rolling Redux in, but stopped short because I figured watching the storage onChange event was reactive enough at first. I didn't want to layering on even more new tech while I was busy tearing up the pavement & refactoring everything. But, we use Redux on the Test Pilot site too and it's super handy. So, tl;dr: :+1:

**Comment by ckprice** [comment]
Hasn't bugged us yet. Maybe if we add more intensive features.
