### ISSUE TITLE
Time picker resets before dropdown closes

### ISSUE THREAD

**Issue by tilgovi** [bwinton/SnoozeTabs#375]
After setting the snooze time, clicking the Snooze button resets the time before closing the menu, making it appear that the selection was not taken into account.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @tilgovi and thanks for your report. For now, the future of the experiment is unsure so I don't think someone will triage your issue until a decision is made. It could either be considered a valid bug and be fixed, or it could be closed due to experiment ending. We'll see in the next weeks/months which one will be.

**Comment by lmorchard** [comment]
Trying to reproduce this, but can't see the issue. I snoozed a tab, picked a date/time, edited the time, clicked "Snooze", and the time looked like what I picked

**Comment by lmorchard** [comment]
Going to close this for now, we can re-open if it happens again or someone can reproduce
