### ISSUE TITLE
latest release 1.0.20

### ISSUE THREAD

**Issue by gherghel** [bwinton/SnoozeTabs#379]
I have 1.0.20 and it is not working (full of bugs). how can I reverse to 1.0.17?

**Comment by SoftVision-CarmenFat** [comment]
Hi @gherghel, thanks for the report.

Can you be more specific, please? In which way Snooze Tabs doesn't work? And what bugs are you encountering? 

Thank you!

**Comment by SoftVision-PaulOiegas** [comment]
Hi @gherghel and thanks for your report. However, this is quite strange since nothing changed on Snooze Tabs since 18th of August. Did you just recently updated to 1.0.20 or you have it for some time now? If you had it for some time, did it recently broke or it was broken since updating?

I'm asking this questions because I want to find out if this is due to Firefox changes, Snooze Tabs or it is because of some changes that occurred recently on your environment. There could be other Firefox extensions that are incompatible with this experiment, or preference changes that could alter its functionality.

Also, can you please share more details about your issue? Some steps to reproduce and a screen recording would be very helpful to debug your issue properly.

**Comment by gherghel** [comment]
The snooze button is not working. Starting today when Snooze Tabs upgraded to 1.0.20. It is strange that on another device 1.0.17 is working perfect, Steps: snooze tab until > pick a date/time. See atached file
[snooze tabs.docx](https://github.com/bwinton/SnoozeTabs/files/1571882/snooze.tabs.docx)

**Comment by gherghel** [comment]
How can I reverse to 1.0.17?

**Comment by AussieGit** [comment]
I have this same issue where the snooze button is not active when you choose your own time/date. The way I to make it work is click the white space just to the left of the drop down date/time box then you can click the snooze button. Annoying little bug but easily overcome. I am using Win 7, FF v57.0.2 & Snooze version 1.0.20 but it has had this bug sinceFF changed to WE

**Comment by SoftVision-CarmenFat** [comment]
The fact that the time picker drop down is cut off and the "Snooze" button doesn't work anymore are known issues (please see #364 and #356 ) and, as @AussieGit said in the previous comment, there is a workaround where you can click the left side of the time picker drop down. This way, the "Snooze" button becomes clickable and can be used as expected.

If you prefer to downgrade to the 1.0.17 version, I can provide you an older Snooze Tab build. Please remember that, in order to avoid its upgrade to version 1.0.20, you have to uncheck the "Update Add-ons Automatically" option from the Add-on Manager. This way, it will remain at the 1.0.17 version until you choose to manually update it.

[snoozetabs-1.0.17_11.04.2017.zip](https://github.com/bwinton/SnoozeTabs/files/1572278/snoozetabs-1.0.17_11.04.2017.zip)

If you have any trouble enabling Snooze Tabs through the .zip file from above,  please let me know.

**Comment by gherghel** [comment]
Thank you. I am waiting 1.0.21 to fix this bug.

**Comment by gherghel** [comment]
Time picker: The drop down does not go beyond 20:56

**Comment by gherghel** [comment]
So, I made my decision. [SoftVision-CarmenFat](url), please guide me, step by step, to downgrade to 1.0.17

**Comment by SoftVision-CarmenFat** [comment]
Sure, please follow the next steps:

1. First, you need to download and unzip the file that I provided you in the previous comment.
2. Go to "about:debugging" page and click on the "Load Temporary Add-on" button.
3. Navigate and enter the unzipped folder.
4. From the unzipped folder, double-click on the "manifest.json" file.
5. Go to "about:addons" page and click on the "Extensions" option.
6. Double click on Snooze Tabs experiment.
7. Click the "Off" radio button from the "Automatic Updates" row, so this way, Snooze Tabs will not update itself.

- Attached is a gif that contains all the steps written above. Please let me know if you have any trouble installing Snooze Tabs this way.
- Please note that these steps are only available for Release and Beta builds. If you use Nightly, there is a different procedure to install it.

![install snooze tabs](https://user-images.githubusercontent.com/26000308/34208907-d11891a4-e598-11e7-99ba-b320d0bb1487.gif)

**Comment by AussieGit** [comment]
This is support over and above what is expected. Well done guys. Not only is it a superb extension but the support offered to Gherghel is 99.9% more than most developers would think about. Most would have said "Google it" or refer to Firefox guidelines for old version extensions. Brilliant. 👏👏

**Comment by SoftVision-CarmenFat** [comment]
Actually, I forgot to mention something important: this way of installing the Snooze Tabs Add-on is temporary, so, when you close and then reopen the browser, the Add-on will be gone and you will have to start all over again the process of installing it. Must note that you won't lose any of your snoozed websites, but this method can be inconvenient since you have to install the Add-on each time you restart the browser.

Another way to install Snooze Tabs without having to repeat the process when reopening the browser is through Nightly or Developer Edition. You can download them from this link: 
- https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly

Once you install Snooze Tabs on one of the 2 mentioned channels (Nightly and Developer Edition), it stays installed no matter how many times you close the browser.

If you choose to install Snooze Tabs on Nightly or Developer Edition, here are the steps you must follow:
1. Download the zip provided 2 comments above.
2. Go to "about:config" and set "xpinstall.signatures.required" pref to "false" value.
3. Go to "about:addons" and click on the "Extensions" option.
4. Drag and drop the zip on the page's empty area.
5. Click the "Add" button on the door hanger and that's kind about it.

This way, you don't need to reinstall Snooze Tabs each time you reopen your browser.

I hope this helps you in some way and sorry for any inconvenience that ugly bug may have caused you.

**Comment by gherghel** [comment]
Thanks. You made my day. When shall we expect 1.0.21?

**Comment by SoftVision-PaulOiegas** [comment]
@gherghel A decision regarding the fate of this experiment wasn't taken yet. It could enter in a redesign period to match the current browser design, or it could be shut down. Probably we'll find out in this quarter what it will be.

**Comment by sNiXx** [comment]
Just wanted to say that this is a fantastic add-on and would love to see how it develops. Don't want to live without it 😄
