### ISSUE TITLE
Don't let this project die

### ISSUE THREAD

**Issue by gabrielqv** [bwinton/SnoozeTabs#389]
thanks for all your work developers, this a tool i use everyday, and that i think with the time and exposure could help a lot of people in their online activities, i would be very sad to see it go, as it was what convinced me to ditch chrome after 3 or 4 years of use

**Comment by lmorchard** [comment]
We are considering graduation plans for this Test Pilot experiment right at this moment. [We've also been working through issues to sprint toward at least one more release](https://github.com/bwinton/SnoozeTabs/issues?q=is%3Aopen+is%3Aissue+milestone%3AESR).

That said, you might want to [start a thread on Discourse](https://discourse.mozilla.org/c/test-pilot/snooze-tabs), since GitHub issues aren't a great place for discussion of this sort. We'll probably discuss plans there once we have something more concrete to say

**Comment by gabrielqv** [comment]
Ok i'm glad that the future holds hope for the extension, yeah casually I already had the discourse thread open, but I see there lots of technical details and suggestions that although could polish more the product I don't know if should be the focus, I care only at the moment that the feature is kept alive and maybe adds sync support  (even if I suppose it's quite a laborious thing to implement)  let me know if you need any feedback usage or another way to show support for your code :)!
