### ISSUE TITLE
The AM and PM text from each snooze option is still in uppercase format

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#411]
[Affected versions]:
- Release 58.0 and up
- Snooze Tabs 1.0.21

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://669-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.kZdit8p/addon.xpi) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website.
2. Click the "Snooze Tabs" button from the toolbar.
3. Observe the "am" and "pm" text from each option.

[Expected result]:
- The text is lowercase and there is no space between the text and the hours.

[Actual result]:
- The text is uppercase and there is space between the text and the hours.

[Notes]:
- Attached a screenshot of the issue:

![am pm is still uppercase](https://user-images.githubusercontent.com/26000308/35512368-3567edba-0508-11e8-9ec9-09691f1a430e.png)

**Comment by lmorchard** [comment]
FWIW, we don't address this at all across locales - [just in en-* locales](https://github.com/bwinton/SnoozeTabs/blame/master/src/lib/time-formats.js#L48). That's because we use built-in date l10n and then hack the resulting string a little. All other locales [get the direct output of date l10n](https://github.com/bwinton/SnoozeTabs/blame/master/src/lib/time-formats.js#L55) rather than this stylized presentation.

So, I can address this for en-* locales, but not comfortable doing it for any others that I don't personally understand.
