### ISSUE TITLE
Allow the user to see a list of previously snoozed tabs

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#44]
Should we have a "history" section that shows previously snoozed & since awakened tabs?

**Comment by sevaan** [comment]
I'd say no. The concept is that Snoozed Tabs are ephemeral. It could be things like "Pop this tab to order these concert tickets when they go on sale" which is useless to return to. Users can save/bookmark import urls using their normal workflows...we're just offering a way to clean/hide tabs they don't need right now.

But...I do think we should ask users about this to double-check.

**Comment by lmorchard** [comment]
Should we defer this out of the initial release and ask users after the experiment gets in their hands? Or is there some user research going on before then?

**Comment by sevaan** [comment]
We can defer this out of the initial release and can query users after.

**Comment by pdehaan** [comment]
If we _do_ end up adding a historical list of snoozes, we'll need to make a UI that allows me to edit that list. There may be some previous snoozes that I don't want appearing in that list for future me or other people to see so I'll want to delete them.

**Comment by albinhh** [comment]
First of all, thanks for all the work for this addon, I'll find it very usefull! So I like to contribute a bit as well with my experience as a UX-designer and a user of this addon:

I think the decision if of if not a history should be implemented should be based on the need of the user for such a history. In general I'll say, all users using the regular history of FF would use a snooze-history as well. I have a example "Pro-History" userstory (more or less):
I had it a few times where i missed a snoozed web-site (I think because I clicked it away). I remember them, because I had them snoozed for the next day. Usually I remember this after a few days and want to look up the sites again. But there is no chance to find the website anymore in the "regular FF -histrory", a snooze-history would be helpfull.

@sevaan 
I'll agree, but...
If I use the snooze function, it would be nice if my "normal workflow" is done for me as well. Of course it's possible to ad the site as a bookmark as well, but if it is saved in a history I won't have to save it as a bookmark anymore which would save me a bit of time/stress => better usability => more user value

hope I could help you guys, if not let me know, and I'll shut up again ;)

**Comment by bwinton** [comment]
We haven't really had a lot of requests for this, so I think I'm going to close it, and if it comes up again, maybe someone will be motivated to write a patch that adds it. 🙂
