### ISSUE TITLE
Backing up your snoozes

### ISSUE THREAD

**Issue by gabrielqv** [bwinton/SnoozeTabs#454]
Hi guys, I really love that this proyect is taking steam , I'm however currently in a hardship, I really want to format and install a new OS on my pc, but knowing that I will lose all my snoozed tabs, that are roughly 200 tabs and counting I would like to know if there are any plans for backing up and mantaining your snoozes, I know there's the list in the bookmarks menu, but revisiting all those tabs and selecting the right snooze again for them feels like a task I could get away with some programming, is there anything that could be done about it, taking into account the graduated status of the extension now that brings it alittle into the spotlight?

**Comment by sNiXx** [comment]
I agree, backup options would be a much needed feature to make the addon feasible for long-term use.
Thanks to the developers for this most useful addon, I've been really enjoying it for the last few months

**Comment by gherghel** [comment]
it is vital.

**Comment by bwinton** [comment]
The bookmarks should contain the wake-up data, so if they get synced, that will be your backup. At least, that's how it worked for me in testing.

**Comment by matt22207** [comment]
@bwinton , how does syncing/restoring work?

- I see the snoozed tabs in my bookmarks, in a subfolder that looks like it is named with the extension's UUID.
- I don't see any specific dates in the bookmarks, so not sure how it would know how to restore the "Snooze Until" date.
- I checked on another computer with the same Firefox profile, and the synced bookmarks are there, but the Snoozed Tab extension doesn't pick it up. Possibly has it's own UUID per computer?

I asked here rather than #466 (which might be more relevant) because that PR was closed in favor of this one. Happy to move to that thread if necessary.

**Comment by bwinton** [comment]
Hmmm… It's been a while since I looked into this, but it looks like, after pinging back and forth from the background task to the browser, we end up at https://github.com/bwinton/SnoozeTabs/blob/a04003b690e33a17015a198fdc2e8dbea5f0ba43/src/background.js#L143-L167, which calls `saveAlarms`, which saves the data into the extension's localStorage.
You can see it from about:debugging#/runtime/this-firefox
and an example I just made looks like `1670594430508-https://github.com/bwinton/SnoozeTabs/blob/a04003b690e33a17015a198fdc2e8dbea5f0ba43/src/background.js#L207:"{"time":1670594430508,"timeType":"tomorrow","title":"SnoozeTabs/background.js at a04003b690e33a17015a198fdc2e8dbea5f0ba43 · bwinton/SnoozeTabs","url":"https://github.com/bwinton/SnoozeTabs/blob/a04003b690e33a17015a198fdc2e8dbea5f0ba43/src/background.js#L207","windowId":3,"icon":"data:image/svg+xml;base64,…"}"`

(The time is pre-pended to the url to form the key, as well as being stored in the json blob.)
