### ISSUE TITLE
Permissions: "Access your data for all websites"?

### ISSUE THREAD

**Issue by jschneid** [bwinton/SnoozeTabs#463]
I enjoyed the Snooze Tabs feature while it was part of Test Pilot (https://testpilot.firefox.com/experiments/snooze-tabs/). I went to install the Snooze Tabs feature again today from the FireFox Addons site (https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/), but saw that it requires the following permissions:

> This add-on can:
> - Access your data for all websites
> - Read and modify bookmarks
> - Display notifications to you
> - Access browser tabs

For security reasons, I generally avoid add-ons with the `Access your data for all websites` permission.  (To a lesser extent, I also don't like to grant `Read and modify bookmarks`.)

Would it be possible for a new version of this add-on to be released that doesn't require these permissions?

**Comment by bwinton** [comment]
Yeah, unfortunately not really, since I need to get the url of any tab you might want to snooze (and save it as a bookmark, and create a new tab with that url), and the only way to get that is to ask for `<all_urls>`, which shows the listed permissions. You can check the code to make sure I'm not doing anything nefarious, but I totally understand if this is a dealbreaker for you.
