### ISSUE TITLE
Set up localization

### ISSUE THREAD

**Issue by lmorchard** [bwinton/SnoozeTabs#55]
This extension should be localize-able. WebExtensions have an [i18n module](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization) available for this.

**Comment by lmorchard** [comment]
One sticking point: Pontoon does not support the JSON format used by the i18n module in Web Extensions. Need to do some more research into what the situation is here, if there's a happy path I'm missing

**Comment by bwinton** [comment]
For TabCenter, I copied [a script](https://github.com/bwinton/TabCenter/blob/master/genlocales) from someone, that converted Pontoon stuff into `jpm` stuff.  I figured something similar here might work?

Oh, the other thing I strongly suggest is making a separate "SnoozeTabs-l10n" repo, so that this one doesn't get flooded with Pontoon commits, and so that we can review the stuff coming in before we merge it.  😉

**Comment by bwinton** [comment]
(We could also lean on the Pontoon folk to support WebExtensions, since this seems to be the direction we're going.  Or we could skip the i18n module, and jump straight to l20n, which seems like the future of l10n support.  So, multiple possible paths…)

**Comment by ckprice** [comment]
@johngruen is this required for initial release?

**Comment by ckprice** [comment]
Moving this to Next after a chat with John. Maybe a follow-up l10n launch for all the things would be good.

**Comment by bwinton** [comment]
Okay, so, @clouserw (or whomever), could you ask the nice Pontoon people to point Pontoon at the `l10n` branch of this repo, and we can see what happens?  😉  Thanks!

**Comment by pdehaan** [comment]
Filed Pontoon portion of this as #170.
