### ISSUE TITLE
Unable to snooze a tab to a date/time in the past

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#73]
Super duper edge case, but oddly SnoozeTabs doesn't try and stop me...

### Steps to reproduce:
1. Go to a page which we want to hypothetically snooze. For example, https://www.mozilla.org/en-US/firefox/new/
1. Open the Browser Console and make sure any previous logs/errors are cleared (for easier debugging).
1. Snooze the tab but pick a specific Date/Time. For example, when selecting a Date, hit "Now" and it should select the current date/time, and disable the "Snooze" button.
1. Click the "Select Time" and hit "Now" button a few more times, and the time picker should scroll to the exact current date/time again and still not let you select the current time.
1. Select a second value a few seconds in the future so the "Snooze" button becomes enabled.
1. Wait a few more seconds so the selected date/time is now _just_ technically in the past (but the "Snooze" button is still enabled).
1. Hit the enabled "Snooze" button.

### Actual results
Nothing happens, and nothing seems to appear in my Developer Tools or Browser Console informing me there was an error.
In order to _actually_ snooze the active tab, I need to quickly select a date a few seconds in the future and then click the Snooze button again while that date is still in the future.

Not sure if we should be aggressively preventing users from snoozing tabs in the past, or if we just shrug it off and then display the snooze tab reminder immediately.

Pretty edge case.

**Comment by pdehaan** [comment]
You can also just reproduce this by Snoozing a tab to a specific date/time, and then immediately clicking the enabled Snooze button, which has no effect (since presumably the exact current date/time is passed by the time you go to click a snooze button).

**Comment by sevaan** [comment]
We definitely need to lose the "Now" option.

Regarding aggressively blocking snoozes from the past or just returning them instantly, I'm okay with whatever would be easiest to implement here (I imagine just returning the tab instantly) as long as we can measure how many people's snoozes are in the past to revisit this decision later with some data.

**Comment by bwinton** [comment]
Don't worry, the "Now" option only shows up in debug builds, for testing.  😀

**Comment by lmorchard** [comment]
> Not sure if we should be aggressively preventing users from snoozing tabs in the past, or if we just shrug it off and then display the snooze tab reminder immediately.

Oh wait, I misinterpreted this bug at first. I thought this was a regression on #50 - wherein the code *did* allow a time selection in the past.

So, yes, we *do* want to aggressively prevent past times on snoozed tabs.  When you click on the button, [there *is* validation code which rejects accepting the action if the selected time is in the past](https://github.com/bwinton/SnoozeTabs/blob/master/src/lib/components/DatePickerPanel.js#L109). If anything, the bug here is that the "Snooze" button does not get *styled* as inactive when time ticks past whatever is selected.

There is also [code that should wake any overdue snoozed tab (even those somehow in the past)](https://github.com/bwinton/SnoozeTabs/blob/master/src/background.js#L128), on the next background wake timer (which should never be in the past but always [at least 5 seconds from now or later](https://github.com/bwinton/SnoozeTabs/blob/master/src/background.js#L116)).

**Comment by pdehaan** [comment]
Yeah, sorry. I didn't mean to imply that it was a regression. I was just fighting with the "Now" button which certainly almost never does what you'd want versus the rollover issue where I accidentally snoozed for a time in the very near future and the button UI wasn't updating.
This has been partially addressed by the removal of the seconds from the time picker, and probably further mitigated by moving the date+time to the same screen.

**Comment by lmorchard** [comment]
> Yeah, sorry. I didn't mean to imply that it was a regression. 

Naw, that wasn't you, that was me just skimming over issues :)

**Comment by lmorchard** [comment]
> We definitely need to lose the "Now" option.

There's also a "Now" link that comes out-of-box with the Calendar component we're using. But, #101 should help address that as part of properly styling & tailoring the component, because it's not a part of the original design spec anyway.
