### ISSUE TITLE
Links opened from "Manage Snoozed Tabs" are not automatically removed after being opened

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/SnoozeTabs#81]
[Affected versions]:
- Nightly 53.0a1
- Snooze Tabs 1.0 (built on 1/10/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0-dev, built on 1/9/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Focus the window with the profile from prerequisites.
2. Navigate to a website and snooze the tab.
3. Click the "Snooze Tabs" button from the browser toolbar.
4. Click the "Manage Snoozed Tabs" button and hover the recently snoozed tab.
5. Click the tab and observe the behavior.

[Expected results]:
- The snoozed tab is opened in a new tab and the entry is automatically removed.

[Actual results]:
- The snoozed tab is opened in a new tab, but the entry is not automatically removed.

[Notes]:
- Attached a screen recording of the issue:
![links opened from manage snoozed tabs are not automatically removed after being opened](https://cloud.githubusercontent.com/assets/18304511/21810259/b952002c-d753-11e6-8757-53814805a23d.gif)

**Comment by sevaan** [comment]
This is a WONTFIX for now (until some user research says otherwise).

The thinking is that the Snooze still stands; this is just a way for the user to get to reopen it if they in the meantime. If a user wants to explicitly remove the snooze, we have the delete button for it. 

It's like if you snooze an email to come back to you next week, but you just want to read something in it...opening that email doesn't cancel the snooze.

**Comment by SoftVision-CiprianMuresan** [comment]
I agree with this. I was just looking for confirmation that this is the desired behavior.
